# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8479bfa11b0b8003aa859b3b28b3856c7711059bd02a3f43afc319774507c95246bc20cee8f115d5a355210292f38de062e60cac50508aa42745486ef2404cd2

test:
  secret_key_base: ccdad18521c3fb350f427f6f9d5a9e1682837bd822a0489746460c7704cef751ab44761ffd4ab2f250d8b70df70d6ee987c76ea06b192e223f099e6c6bd27ef4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
